# Generated by Django 4.0.1 on 2022-01-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
